# Integration test server configuration with middleware
# Configures middleware for integration testing environment

middleware:
  # HTTP header middleware - extracts user ID from X-User-ID header
  - type: "http-header"
    config:
      header: "X-User-ID"      # HTTP header name to extract
      parameter: "user_id"     # SQL parameter name to set
      required: false          # Whether the header is required
